// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHKN9BNtUbwtjradO0-2WTsNOil3yy0GE',
    appId: '1:1029148776285:web:4de1aa0faab7d93c937ab4',
    messagingSenderId: '1029148776285',
    projectId: 'fir-bc0ba',
    authDomain: 'fir-bc0ba.firebaseapp.com',
    storageBucket: 'fir-bc0ba.firebasestorage.app',
    measurementId: 'G-TQK8TVLTWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHKN9BNtUbwtjradO0-2WTsNOil3yy0GE',
    appId: '1:1029148776285:android:4de1aa0faab7d93c937ab4',
    messagingSenderId: '1029148776285',
    projectId: 'fir-bc0ba',
    storageBucket: 'fir-bc0ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHKN9BNtUbwtjradO0-2WTsNOil3yy0GE',
    appId: '1:1029148776285:ios:4de1aa0faab7d93c937ab4',
    messagingSenderId: '1029148776285',
    projectId: 'fir-bc0ba',
    storageBucket: 'fir-bc0ba.firebasestorage.app',
    iosBundleId: 'com.example.storRoses1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHKN9BNtUbwtjradO0-2WTsNOil3yy0GE',
    appId: '1:1029148776285:ios:4de1aa0faab7d93c937ab4',
    messagingSenderId: '1029148776285',
    projectId: 'fir-bc0ba',
    storageBucket: 'fir-bc0ba.firebasestorage.app',
    iosBundleId: 'com.example.storRoses1',
  );
}